CREATE TABLE MONITOR_HOST_STATUS (
    HOST_NAME VARCHAR2(500),
    STATUS VARCHAR2(50) NOT NULL,
    FAILURE_COUNT NUMBER,
    MESSAGE_COUNT NUMBER,
    LAST_NOTIFICATION TIMESTAMP,
    LAST_UPDATED TIMESTAMP,
    CONSTRAINT PK_MONITOR_HOST_STATUS PRIMARY KEY (HOST_NAME)
);

CREATE TABLE MONITOR_LOG (
    HOST_NAME VARCHAR2(500),
    LABEL VARCHAR2(2000),
    LAST_SAMPLE TIMESTAMP,
    DURATION NUMBER,
    SUCCESS VARCHAR2(10),
    CONSTRAINT PK_MONITOR_LOG PRIMARY KEY (HOST_NAME, LABEL)
);

CREATE TABLE MONITOR_ERRORS (
    HOST_NAME VARCHAR2(500),
    LABEL VARCHAR2(2000),
    FAILURE_DATE TIMESTAMP,
    STATUS VARCHAR2(50),
    EMAIL_SUBJECT VARCHAR2(1000),
    EMAIL_BODY VARCHAR2(4000),
    EMAIL_SENT VARCHAR2(10)
);